server:
  port: 80

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cooperative
    username: root
    password: maibok
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
